toolchain("arm-himix200-linux")
    set_kind("standalone")
    set_sdkdir("/opt/hisi-linux/x86-arm/arm-himix200-linux")
    set_bindir("/opt/hisi-linux/x86-arm/arm-himix200-linux/bin")
toolchain_end()
